[core-01]
   uuid = "4420CA07-3C45-4110-86D7-D999D9FB6E2E"
   channel = "alpha"
   volume = "root.img"
   cloud_config = "cloud-init/user-data-format-root"
   cpus = 1
   memory = "1024"
   local = "true"
