[core-01]
   uuid = "D1024138-F21A-4C61-8F40-ADCFC358D942"
   channel = "alpha"
   volume = "root.img"
   cloud_config = "cloud-init/user-data-format-root"
   cpus = 1
   memory = "1024"
   local = "true"
